from fpdf import FPDF
projeto = input('Insira o nome do projeto: ')
carga_horária = int(input('Insira a quantidade estimada de horas: '))
valor_hora = float(input('Insira o valor da hora trabalhada: '))
prazo = input('Insira o prazo de execução: ')
valor_final = valor_hora * carga_horária
print(projeto)
print(f'Valor do projeto: R${valor_final :.2f}')
pdf = FPDF()
pdf.add_font('Poppins', '', 'fonts/poppins.ttf', uni=True)
pdf.add_page()
pdf.set_font('Poppins')
pdf.image('template-orçamento.png', x = 0, y = 0)
pdf.text(115, 145, projeto)
pdf.text(115, 160, str(f'{carga_horária} horas'))
pdf.text(115, 175, str(f'R$ {valor_hora :.2f}'))
pdf.text(115, 190, prazo)
pdf.text(115, 205, str(f'R$ {valor_final :.2f}'))
pdf.output('Orçamento.pdf')
print('Orçamento gerado com sucesso!')
